name: Deploy App
on:
  push:
    branches:
      - live # Trigger this workflow when code is pushed to the 'live' branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      REACT_APP_SITE_NAME: ${{ secrets.REACT_APP_SITE_NAME }}
      REACT_APP_LOGO_PATH: ${{ secrets.REACT_APP_LOGO_PATH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.12.0'
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Clean dependencies
        run: |
          rm -f package-lock.json
          npm cache clean --force
          rm -rf node_modules
      - name: Install dependencies
        run: npm install --force
      - name: Build project
        run: CI=false npm run build
      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Transfer build to server
        run: |
          scp -r -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa build user@${{ secrets.SERVER_IP }}:/var/www/html/
          # If you are using static export, replace 'build' with 'out'
      - name: Deploy on server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa user@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            echo "Connected to server"
            sudo rm -rf /var/www/html/my-app-backup # Optional: Backup previous deployment
            sudo cp -r /var/www/html/my-app /var/www/html/my-app-backup # Optional: Backup current deployment
            sudo rm -rf /var/www/html/my-app/*
            sudo cp -r /var/www/html/build/. /var/www/html/my-app/
            sudo rm -rf /var/www/html/build # Clean up build directory on the server
            echo "Deployment complete"
          EOF
          # If you are using static export, replace the 'cp' commands with:
          # sudo cp -r /var/www/html/out/. /var/www/html/my-app/
      - name: Health Check
        run: |
          curl -f https://${{ secrets.HEALTH_CHECK_URL }} || (echo "Health check failed!" && exit 1)
      - name: Notify Success
        run: echo "✅ Deployment successful!"